site_name: Database Folder
repo_url: https://github.com/RafaelGB/obsidian-db-folder
edit_uri: edit/master/docs/docs/
nav:
  - Get started: "index.md"
  - Features:
      - Sources: "features/Sources.md"
      - Columns: "features/Columns.md"
      - Properties: "features/Properties.md"
      - Notes: "features/Notes.md"
      - Viewing data: "features/Viewing data.md"
      - Relations: "features/Relations.md"
      - Formulas: "features/Formulas.md"
  - About: "about.md"
  - FAQ: "faq.md"
  - Media:
      - videos: "media/videos.md"
  - Contributing:
      - Documentation: "contributing/documentationContribution.md"
      - Developers: "contributing/developersContribution.md"
  - Changelog: "changelog.md"
theme:
  name: material
  logo: assets/obsidian.png
  icon:
    repo: fontawesome/brands/github-square
plugins:
  - search
